#! /usr/bin/bash

docker build \
--build-arg REACT_APP_BACKEND_URL="https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}" \
--build-arg REACT_APP_AWS_PROJECT_REGION="$AWS_DEFAULT_REGION" \
--build-arg REACT_APP_AWS_COGNITO_REGION="$AWS_DEFAULT_REGION" \
--build-arg REACT_APP_AWS_USER_POOLS_ID="us-east-1_019cAtPHi" \
--build-arg REACT_APP_CLIENT_ID="6bdss0f1867al22lee8jd3duku" \
-t frontend-react-js \
-f Dockerfile.prod \
.